// Generated by the gRPC protobuf plugin.
// If you make any local change, they will be lost.
// source: SxDataTransfer.proto

#include "SxDataTransfer.pb.h"
#include "SxDataTransfer.grpc.pb.h"

#include <grpc++/impl/codegen/async_stream.h>
#include <grpc++/impl/codegen/async_unary_call.h>
#include <grpc++/impl/codegen/channel_interface.h>
#include <grpc++/impl/codegen/client_unary_call.h>
#include <grpc++/impl/codegen/method_handler_impl.h>
#include <grpc++/impl/codegen/rpc_service_method.h>
#include <grpc++/impl/codegen/service_type.h>
#include <grpc++/impl/codegen/sync_stream.h>
namespace TSDStreaming {

static const char* DataTransfer_method_names[] = {
  "/TSDStreaming.DataTransfer/MbSentDataToTsd",
};

std::unique_ptr< DataTransfer::Stub> DataTransfer::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  std::unique_ptr< DataTransfer::Stub> stub(new DataTransfer::Stub(channel));
  return stub;
}

DataTransfer::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_MbSentDataToTsd_(DataTransfer_method_names[0], ::grpc::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status DataTransfer::Stub::MbSentDataToTsd(::grpc::ClientContext* context, const ::TSDStreaming::MbDataTransfer& request, ::TSDStreaming::MbDatRecvResponse* response) {
  return ::grpc::BlockingUnaryCall(channel_.get(), rpcmethod_MbSentDataToTsd_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::TSDStreaming::MbDatRecvResponse>* DataTransfer::Stub::AsyncMbSentDataToTsdRaw(::grpc::ClientContext* context, const ::TSDStreaming::MbDataTransfer& request, ::grpc::CompletionQueue* cq) {
  return new ::grpc::ClientAsyncResponseReader< ::TSDStreaming::MbDatRecvResponse>(channel_.get(), cq, rpcmethod_MbSentDataToTsd_, context, request);
}

DataTransfer::Service::Service() {
  AddMethod(new ::grpc::RpcServiceMethod(
      DataTransfer_method_names[0],
      ::grpc::RpcMethod::NORMAL_RPC,
      new ::grpc::RpcMethodHandler< DataTransfer::Service, ::TSDStreaming::MbDataTransfer, ::TSDStreaming::MbDatRecvResponse>(
          std::mem_fn(&DataTransfer::Service::MbSentDataToTsd), this)));
}

DataTransfer::Service::~Service() {
}

::grpc::Status DataTransfer::Service::MbSentDataToTsd(::grpc::ServerContext* context, const ::TSDStreaming::MbDataTransfer* request, ::TSDStreaming::MbDatRecvResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace TSDStreaming

